//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ui.rc
//
#define IDD_DIALOG_MAIN                 101
#define IDI_ICON_MAIN                   103
#define IDD_DIALOG_ABOUT                104
#define IDD_DIALOG_PEINFO               105
#define IDD_DIALOG_SECTION              109
#define IDD_DIALOG_DIR                  110
#define IDD_DIALOG_DIRDETAIL            111
#define IDC_BUTTON_OPEN                 1000
#define IDC_BUTTON_ABOUT                1001
#define IDC_BUTTON_QUIT                 1002
#define IDC_LIST_PROCESS                1003
#define IDC_LIST_MODULE                 1004
#define IDC_EDIT_PEINFO_ENTRYPOINT      1005
#define IDC_EDIT_PEINFO_IMAGEBASE       1006
#define IDC_EDIT_PEINFO_SIZEOFIMAGE     1007
#define IDC_EDIT_PEINFO_BASEOFCODE      1008
#define IDC_EDIT_PEINFO_BASEOFDATA      1009
#define IDC_EDIT_PEINFO_SECTIONALIGN    1010
#define IDC_EDIT_PEINFO_FILEALIGN       1011
#define IDC_EDIT_PEINFO_MAGIC           1012
#define IDC_BUTTON_PEINFO_SECTION       1013
#define IDC_EDIT_PEINFO_SUBSYS          1014
#define IDC_EDIT_PEINFO_NUMBEROFSECTION 1015
#define IDC_EDIT_PEINFO_TIMESTAMP       1016
#define IDC_EDIT_PEINFO_SIZEOFHEADER    1017
#define IDC_EDIT_PEINFO_CHARC           1018
#define IDC_EDIT_PEINFO_CHECKSUM        1019
#define IDC_EDIT_PEINFO_SIZEOFOPHEADER  1020
#define IDC_EDIT_PEINFO_NUMBEROFRVAANDSIZES 1021
#define IDC_BUTTON_PEINFO_DIR           1022
#define IDC_BUTTON_PEINFO_QUIT          1023
#define IDC_LIST_SECTIONS               1024
#define IDC_EDIT_DIR_EXPORT_SIZE        1026
#define IDC_BUTTON_DIR_EXPORT           1027
#define IDC_EDIT_DIR_IMPORT_SIZE        1028
#define IDC_BUTTON_DIR_IMPORT           1029
#define IDC_BUTTON_DIR_RES              1030
#define IDC_BUTTON_DIR_RELOC            1031
#define IDC_EDIT_DIR_RES_SIZE           1032
#define IDC_BUTTON_DIR_BOUNDIMPORT      1033
#define IDC_EDIT_DIR_EXCEPTION_SIZE     1034
#define IDC_BUTTON_DIR_IAT              1035
#define IDC_EDIT_DIR_SECURITY_SIZE      1036
#define IDC_BUTTON_DIR_QUIT             1037
#define IDC_EDIT_DIR_BASERELOC_SIZE     1038
#define IDC_EDIT_DIRDETAIL              1038
#define IDC_EDIT_DIR_DEBUG_SIZE         1040
#define IDC_EDIT_DIR_COPYRIGHT_SIZE     1042
#define IDC_EDIT_DIR_GLOBALPTR_SIZE     1044
#define IDC_EDIT_DIR_TLS_SIZE           1046
#define IDC_EDIT_DIR_LOADCONFIG_SIZE    1048
#define IDC_EDIT_DIR_BOUNDIMPORT_SIZE   1050
#define IDC_EDIT_DIR_IAT_SIZE           1052
#define IDC_EDIT_DIR_DELAYIMPORT_SIZE   1054
#define IDC_EDIT_DIR_COM_SIZE           1056
#define IDC_EDIT_DIR_RETAIN_SIZE        1058
#define IDC_EDIT_DIR_EXPORT_RVA         1059
#define IDC_EDIT_DIR_IMPORT_RVA         1060
#define IDC_EDIT_DIR_RES_RVA            1061
#define IDC_EDIT_DIR_EXCEPTION_RVA      1062
#define IDC_EDIT_DIR_SECURITY_RVA       1063
#define IDC_EDIT_DIR_BASERELOC_RVA      1064
#define IDC_EDIT_DIR_DEBUG_RVA          1065
#define IDC_EDIT_DIR_COPYRIGHT_RVA      1066
#define IDC_EDIT_DIR_GLOBALPTR_RVA      1067
#define IDC_EDIT_DIR_TLS_RVA            1068
#define IDC_EDIT_DIR_LOADCONFIG_RVA     1069
#define IDC_EDIT_DIR_BOUNDIMPORT_RVA    1070
#define IDC_EDIT_DIR_IAT_RVA            1071
#define IDC_EDIT_DIR_DELAYIMPORT_RVA    1072
#define IDC_EDIT_DIR_COM_RVA            1073
#define IDC_EDIT_DIR_RETAIN_RVA         1074

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
